services:
  rightsize-backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: rightsize-backend
    environment:
      RIGHTSIZE_SIMULATION_MODE: "true"
      RIGHTSIZE_DB_FILE: /data/rightsize.db
      RIGHTSIZE_CPU_HOUR_COST_INR: "3.5"
    ports:
      - "8000:8000"
    volumes:
      - rightsize-data:/data

  rightsize-operator:
    profiles:
      - operator
    build:
      context: .
      dockerfile: Dockerfile.operator
    container_name: rightsize-operator
    environment:
      RIGHTSIZE_AI_BRAIN_URL: http://rightsize-backend:8000
      RIGHTSIZE_DB_FILE: /data/rightsize.db
      RIGHTSIZE_MIN_CONFIDENCE: "0.50"
    volumes:
      - rightsize-data:/data
      - ${USERPROFILE}/.kube:/root/.kube:ro
    depends_on:
      - rightsize-backend

volumes:
  rightsize-data:
